### ISSUE TITLE
Exit code 101

### ISSUE THREAD

**Issue by alexvetter** [anthonygelibert/QLColorCode#6] opened 2016-04-04 13:22 UTC
Having some problems after installation of the latest available version (homebrew). I get following error in my Console.app:

```
04/04/16 15:09:54,059 QuickLookSatellite[72485]: QLColorCode: colorize.sh failed with exit code 101.  Command was ('/opt/homebrew-cask/Caskroom/qlcolorcode/2.0.6/QLColorCode.qlgenerator/Contents/Resources/colorize.sh' '/opt/homebrew-cask/Caskroom/qlcolorcode/2.0.6/QLColorCode.qlgenerator/Contents/Resources' '/path/to/javascript/file.js' 0).
```

Calling the script from shell I get following error:

```
go4it:4: parse error: condition expected: =
go4it:9: command not found: -T
cat: 0: No such file or directory
go4it:4: parse error: condition expected: =
go4it:9: command not found: -T
cat: 0: No such file or directory
```

Running on El Capitan 10.11.4 (15E65) with qlcolorcode 2.0.6 from homebrew.

**Comment by anthonygelibert** [comment] 2016-04-07 19:01
Sorry for the delay… Can you indicate me your highlight version, please?

**Comment by alexvetter** [comment] 2016-04-09 09:13
I'm using the `highlight` which was installed as a dependency of `qlcolorcode`. It's strange but `highlight` is in the [legacy homebrew repo](https://github.com/Homebrew/legacy-homebrew/blob/master/Library/Formula/highlight.rb).

```
 highlight version 3.27
 Copyright (C) 2002-2016 Andre Simon <andre.simon1 at gmx.de>

 Argparser class
 Copyright (C) 2006-2008 Antonio Diaz Diaz <ant_diaz at teleline.es>

 Artistic Style Classes (2.05)
 Copyright (C) 2006-2014 by Jim Pattee <jimp03 at email.com>
 Copyright (C) 1998-2002 by Tal Davidson

 Diluculum Lua wrapper (1.0)
 Copyright (C) 2005-2013 by Leandro Motta Barros

 xterm 256 color matching functions
 Copyright (C) 2006 Wolfgang Frisch <wf at frexx.de>

 This software is released under the terms of the GNU General Public License.
 For more information about these matters, see the file named COPYING.
```

**Comment by alexvetter** [comment] 2016-04-09 09:27
more information

```
$ which highlight
/usr/local/bin/highlight
```

```
$ ll /usr/local/bin/highlight
/usr/local/bin/highlight -> ../Cellar/highlight/3.27/bin/highlight
```

**Comment by cc941201** [comment] 2016-04-15 15:35
`defaults write org.n8gray.QLColorCode pathHL /usr/local/bin/highlight` seems to be able to solve the problem.

**Comment by alexvetter** [comment] 2016-04-15 15:59
Just tried it. It works fine now. But I would argue, that it's more a workaround than a solution to this problem. I think there are many users which just type `brew cask install qlcolorcode` into there terminal and hit enter. They don't bother where the highlight comes from and that the `defaults` should be overwritten.

I think one solution would be to modify the homebrew Formula and change the `defaults` while installation.

**Comment by cc941201** [comment] 2016-04-15 16:08
I've read the source code, and it does set the defaults automatically. However, the code fails silently.

It is possible that OS X 10.11 forbids QuickLook plugin to write defaults.

**Comment by alexvetter** [comment] 2016-04-15 16:13
Thanks for the insight. But than again setting the `defaults` in the Formula could be one "solution". I don't have a OS X 10.10 around where I could test it.
Another thought... why not use the `$PATH` variable to find `highlight`?

**Comment by cc941201** [comment] 2016-04-15 16:16
It currently runs `which highlight` and records the result. It is equivalent of using `$PATH`.

**Comment by alexvetter** [comment] 2016-04-15 16:18
Thanks again. I will shut up now. Clearly you have looked more into the problem than I did.

**Comment by cc941201** [comment] 2016-04-15 16:54
I was wrong earlier. It wasn't caused by defaults. Instead, calling `which highlight` fails.

I don't know how to debug a QuickLook plugin so I inserted a lot of `NSLog`. The function works fine when copied elsewhere.

**Comment by sy2002** [comment] 2016-04-15 19:30
Thank you @cc941201 and @alexvetter . Your discussion was very helpful for me, as I had the same problem as alexvetter and as cc941201's solution also solved the problem on my side. Maybe @anthonygelibert can solve the "which highlight" problem? When I worked with OSX 10.8, everything worked fine. When I upgraded to El Capitan, the problem arose.

**Comment by anthonygelibert** [comment] 2016-04-15 22:31
Hi @alexvetter, @cc941201 and @sy2002. Thank you for the time passed on this issue. 

The "org.n8gray.QLColorCode" solution was my implementation before @saagarjha adds the PATH auto-detection feature. It seems that it was a good idea but only for <10.11 version like @cc941201 explained. 

I will publish an official release with the fix ASAP.

**Comment by saagarjha** [comment] 2016-04-15 23:41
Just uninstalled and reinstalled QLColorCode to verify this, I can't seem to replicate it. It's odd because the postflight block that @alexvetter mentioned didn't seem to work for me (after a 'brew cask install qlcolorcode'), so I removed it and replaced it with this, which on my (10.11.5 (15F18b)) machine works every time; it recreates pathHL no matter what I do to remove it.

Here's my sequence of removing and reinstalling, if anyone wants to check.

```
$ sudo rm -r ~/Library/QLColorCode.qlgenerator/
$ defaults delete org.n8gray.QLColorCode pathHL
$ defaults read org.n8gray.QLColorCode pathHL
The domain/default pair of (org.n8gray.QLColorCode, pathHL) does not exist
$ sudo brew cask uninstall qlcolorcode
$ qlmanage -r # flush out the old one, hopefully
$ sudo brew cask install qlcolorcode
$ defaults read org.n8gray.QLColorCode pathHL
The domain/default pair of (org.n8gray.QLColorCode, pathHL) does not exist
# Quicklook some code file
$ defaults read org.n8gray.QLColorCode pathHL
/usr/local/bin/highlight

```

**Comment by cc941201** [comment] 2016-04-15 23:57
`brew cask` doesn't need `sudo`, and I don't know what happens if it is run as root.

Also, `QLColorCode.qlgenerator` is at `~/Library/QuickLook` on my machine, perhaps homebrew will install it to `/Library/QuickLook` as root.

**Comment by anthonygelibert** [comment] 2016-04-16 00:06
On my machine, I can confirm that I've a difference between an installation of the plugin in ~/Libary and /Library

**Comment by saagarjha** [comment] 2016-04-16 00:08
Sorry, I ran them with `sudo` first then switched; I was using `apt-get` recently and was in the habit. `brew` doesn't run with sudo, BTW, so I immediately ran it without. I just copied the wrong one from my bash history.

**Comment by saagarjha** [comment] 2016-04-16 00:23
Ok, I've re-added the postflight block in [homebrew-cask](https://github.com/caskroom/homebrew-cask/pull/20574). Could someone try reinstalling after it's merged and seeing if the issue persists?

**Comment by sy2002** [comment] 2016-04-16 16:47
@saagarjha yes, I will test it. Right now I tried a "brew cask update" and it seems, that the new qlcolorcode (2.0.7) from this repo that @anthonygelibert did, is not yet referenced in cask. I assume I should wait with the test until this is done.  - OR - do @saagarjha 's comments mean, that re-adding the postflight block is already fixing qlcolorcode (2.0.6) and therefore (2.0.7) is "not really needed" to fix this?

**Comment by cc941201** [comment] 2016-04-16 17:01
2.0.7 is for people who installed qlcolorcode by themselves in `~/Library/QuickLook` on 10.11. Postflight block is for people who didn't install homebrew at `/usr/local`.

**Comment by saagarjha** [comment] 2016-04-16 22:38
@cc941201 How exactly does your fix work, for future reference?
From the [homebrew docs](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/FAQ.md),
> /usr/local/bin is already in your PATH.  

Why do you need to explicitly add it?

**Comment by cc941201** [comment] 2016-04-17 01:09
@saagarjha OS X 10.11 ignores `/etc/paths`, and set `$PATH` to `/usr/bin:/bin:/usr/sbin:/sbin` for QuickLook plugins. Those four folders are protected by SIP, so it guarantees nothing installed by user is in the `$PATH` which might override system builtin programs. Therefore, `which highlight` will unlikely find anything on OS X 10.11.

**Comment by saagarjha** [comment] 2016-04-17 02:53
Is this due to SIP? Might be causing issues, since I have it disabled.

**Comment by cc941201** [comment] 2016-04-17 03:04
Perhaps, though the [documentation](https://developer.apple.com/library/mac/documentation/Security/Conceptual/System_Integrity_Protection_Guide/Introduction/Introduction.html) didn't mention it.

**Comment by alexvetter** [comment] 2016-04-17 10:36
Reinstalled qlcolorcode and the new postflight step worked as it should.

```
$ defaults delete org.n8gray.QLColorCode
$ brew cask uninstall --force qlcolorcode
$ brew uninstall highlight
$ brew cleanup && brew cask cleanup && brew update
$ qlmanage -r
$ brew cask install qlcolorcode
$ defaults read org.n8gray.QLColorCode
```

**Closed** 2016-04-25 21:12 UTC
Labels: homebrew
